from typing import Annotated, Optional

import typer
from rich import print as rprint

from mailmon.config import Config
from mailmon.llm import Classifier
from mailmon.mailbox import JMAPBackend
from mailmon.planner import Plan, PlanAction, Planner

app = typer.Typer()
config = Config.from_env()
backend = JMAPBackend(config.jmap)


@app.command(help="Debug prompts generated by mailmon for the LLM classifier")
def prompt(email_id: Optional[str] = None):
    classifier = Classifier(config, backend.get_mailboxes())
    planner = Planner(config, classifier)
    rprint(":robot: [bold green]System Prompt:[/bold green]\n")
    print(planner.classifier.system_prompt())

    if email_id and (email := backend.get_email(email_id)):
        print()
        rprint(":man_medium_skin_tone: [bold green]User Prompt:[/bold green]\n")
        print(planner.classifier.user_prompt(email))


@app.command(help="Generate a plan for how we will classify emails")
def plan(
    email_id: Annotated[
        Optional[str],
        typer.Option(
            "--email", help="Run plan for a specific email id", metavar="EMAIL_ID"
        ),
    ] = None,
    regenerate: Annotated[
        bool, typer.Option(help="Regenerate any persisted plans")
    ] = False,
):
    emails = []
    if email_id and (email := backend.get_email(email_id)):
        emails = [email]
    elif inbox := backend.get_mailbox("Inbox"):
        emails = backend.get_emails(inbox)
    classifier = Classifier(config, backend.get_mailboxes())
    planner = Planner(config, classifier)
    for email in emails:
        plan = planner.plan(email, regenerate)
        print(f"[{email.id}] {email.formatted_from()}:", email.subject)
        print(f"{plan}\n")


@app.command(help="Apply the generate classify plans and update emails")
def apply(
    email_id: Annotated[
        Optional[str],
        typer.Option(
            "--email", help="Run plan for a specific email id", metavar="EMAIL_ID"
        ),
    ] = None,
    regenerate: Annotated[
        bool, typer.Option(help="Regenerate any persisted plans")
    ] = False,
):
    mailboxes = backend.get_mailboxes()
    classifier = Classifier(config, backend.get_mailboxes())
    planner = Planner(config, classifier)
    plans: list[Plan] = []

    if not email_id:
        plans = planner.get_all()
    elif (plan := planner.get(email_id)) is not None:
        plans = [plan]

    for plan in plans:
        if plan.action == PlanAction.MOVE:
            targets = list(mailboxes[target] for target in plan.targets)
            if backend.move_email(plan.email_id, targets):
                if (
                    updated := backend.get_email(plan.email_id)
                ) and updated.mailbox_ids:
                    mailbox_names = [
                        backend.get_mailbox_name(mb)
                        for mb in updated.mailbox_ids.keys()
                    ]
                    planner.delete(plan.email_id)
                    print(f"[{plan.email_id}] -> [{', '.join(mailbox_names)}]")


@app.command(help="Rerun plan for a specifc set of plans")
def replan(
    email_id: Annotated[
        Optional[str],
        typer.Option(
            "--email", help="Rerun plan for a specific email id", metavar="EMAIL_ID"
        ),
    ] = None,
    target_folder: Annotated[
        Optional[str],
        typer.Option(
            "--target",
            help="Rerun plan for a specific target folder",
            metavar="FOLDER_NAME",
        ),
    ] = None,
):
    classifier = Classifier(config, backend.get_mailboxes())
    planner = Planner(config, classifier)
    plans: list[Plan] = []

    if email_id and (plan := planner.get(email_id)) is not None:
        plans.append(plan)

    if target_folder:
        plans.extend(planner.get_by_target(target_folder))

    for plan in plans:
        if email := backend.get_email(plan.email_id):
            planner.plan(email, regenerate=True)
            print(f"[{email.id}] {email.formatted_from()}:", email.subject)
            print(f"{plan}\n")


def main() -> int:
    return app()
